name: app_registro_perfil
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.2
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

# Icono de la app: pon tu imagen en assets/icon/app_icon.png (1024x1024 PNG)
# Luego ejecuta: dart run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/icon/app_icon.png"
  android: true
  ios: true
